### ISSUE TITLE
Upgrade 5.2.2 failed on MacOS 10.13.3

### ISSUE THREAD

**Issue by Chem-Lab** [phusion/homebrew-passenger-enterprise#1]
brew upgrade passenger-enterprise nginx-passenger-enterprise gives the following:

==> rake apache2
==> rake nginx
==> /usr/bin/ruby ./dev/install_scripts_bootstrap_code.rb --ruby /usr/local/Cellar/passenger-enterprise/5.2.2/libexec/src/ruby_supportlib /usr/local/Cellar/passe
==> /usr/bin/ruby ./bin/passenger-config compile-nginx-engine
Last 15 lines from /Users/frank/Library/Logs/Homebrew/passenger-enterprise/04.passenger-config:
	from /private/tmp/passenger-enterprise-20180329-1710-jygzx2/passenger-enterprise-server-5.2.2/src/ruby_supportlib/phusion_passenger.rb:224:in `require_passenger_lib'
	from /private/tmp/passenger-enterprise-20180329-1710-jygzx2/passenger-enterprise-server-5.2.2/src/ruby_supportlib/phusion_passenger/config/nginx_engine_compiler.rb:14:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /private/tmp/passenger-enterprise-20180329-1710-jygzx2/passenger-enterprise-server-5.2.2/src/ruby_supportlib/phusion_passenger.rb:224:in `require_passenger_lib'
	from /private/tmp/passenger-enterprise-20180329-1710-jygzx2/passenger-enterprise-server-5.2.2/src/ruby_supportlib/phusion_passenger/config/compile_nginx_engine_command.rb:12:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /private/tmp/passenger-enterprise-20180329-1710-jygzx2/passenger-enterprise-server-5.2.2/src/ruby_supportlib/phusion_passenger.rb:224:in `require_passenger_lib'
	from /private/tmp/passenger-enterprise-20180329-1710-jygzx2/passenger-enterprise-server-5.2.2/src/ruby_supportlib/phusion_passenger/config/main.rb:167:in `lookup_command_class_by_class_name'
	from /private/tmp/passenger-enterprise-20180329-1710-jygzx2/passenger-enterprise-server-5.2.2/src/ruby_supportlib/phusion_passenger/config/main.rb:152:in `block in lookup_command_class_by_argv'
	from /private/tmp/passenger-enterprise-20180329-1710-jygzx2/passenger-enterprise-server-5.2.2/src/ruby_supportlib/phusion_passenger/config/main.rb:150:in `each'
	from /private/tmp/passenger-enterprise-20180329-1710-jygzx2/passenger-enterprise-server-5.2.2/src/ruby_supportlib/phusion_passenger/config/main.rb:150:in `lookup_command_class_by_argv'
	from /private/tmp/passenger-enterprise-20180329-1710-jygzx2/passenger-enterprise-server-5.2.2/src/ruby_supportlib/phusion_passenger/config/main.rb:58:in `run!'
	from ./bin/passenger-config:22:in `<main>'

**Comment by OnixGH** [comment]
Insufficient information to determine the issue. Further picked up by Passenger Enterprise support.
